draft/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
	url(r'^getathletes', views.league_get_available, name='league_get_available'),
	url(r'^getplayers', views.league_get_players, name='league_get_players'),
]

rowing/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^runleague/', include('runleague.urls', namespace="runleague")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^postman/', include('postman.urls', namespace="postman", app_name="postman")),
    url(r'^draft/', include('draft.urls', namespace="draft")),
	]

runleague/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^about', views.AboutView.as_view(), name='about'),
	url(r'^maketeam/success', views.TeamSuccessView.as_view(), name='make_team_success'),
	url(r'^newleague/success', views.LeagueSuccessView.as_view(), name='make_league_success'),
    url(r'^team/(?P<team_id>[0-9]+)/$', views.team_detail, name='team_detail'),
    url(r'^team', views.my_team_detail, name='my_team_detail'),
    url(r'^(?P<page_id>[0-9]+)/$', views.team_page, name='team_page'),
	url(r'^editteam/add/(?P<athlete_id>[0-9]+)/$', views.athlete_add, name='athlete_add'),
	url(r'^editteam/remove/(?P<athlete_id>[0-9]+)/$', views.athlete_remove, name='athlete_remove'),
	url(r'^editname', views.team_edit_name, name='team_edit_name'),
	url(r'^addathlete', views.team_add_athlete, name='team_add_athlete'),
	url(r'^removeathlete', views.team_remove_athlete, name='team_remove_athlete'),
	url(r'^get_athletes(.)*', views.team_get_athletes, name='team_athlete_get'),
	url(r'^tradeathlete', views.team_trade_athlete, name='team_trade_athlete'),
    url(r'^signin', views.sign_in, name='sign_in'),
    url(r'^signout', views.sign_out, name='sign_out'),
	url(r'^athlete/(?P<athlete_id>[0-9]+)/$', views.athlete_detail, name='athlete_detail'),
	url(r'^signup', views.sign_up, name='sign_up'),
	url(r'^league/(?P<league_id>[0-9]+)/$', views.league_detail, name='league_detail'),
	url(r'^league', views.my_league_detail, name='my_league_detail'),
	url(r'^editleague', views.league_edit, name='league_edit'),
	url(r'^kickuser/(?P<user_id>[0-9]+)/$', views.league_kick_user, name='league_kick_user'),
	url(r'^maketeam', views.make_team, name='make_team'),
	url(r'^newleague', views.new_league, name='new_league'),
    ]

templates/rowing/base.html
<!DOCTYPE html>
<html lang='en' xml:lang='en'>
<head>
	<title>Fantasy Rowing - {% block title %}Title{% endblock %}</title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'mainstylesheet.css' %}" />
	{% block extrahead %}{% endblock %}
	</head>
<body>
	<div class="top-bar">
		{% if user.is_authenticated %}
		<p>{{ user.username }} <a href="{% url 'runleague:sign_out' %}">Sign out</a></p>
		<a href="{% url 'postman:inbox' %}">Messages</a>
		{% else %}
		<a href="{% url 'runleague:sign_in' %}">Sign in</a>
		{% endif %}
	</div>
	<div class="title-bar">
		<h1 id="title">Get Money</h1>
	</div>
	<div class="nav-container">
		<ul class="nav-bar">
			<li>
				<a href="{% url 'runleague:index' %}">Home</a>
			</li>
			<li>
				<a href="{% url 'runleague:about' %}">About</a>
			</li>
			<li>
				<a href="{% url 'runleague:my_team_detail' %}">Team</a>
			</li>
			<li>
				<a href="{% url 'runleague:my_league_detail' %}">League</a>
			</li>
			<li>
				<a href="{% url 'draft:main' %}">Draft Team</a>
			</li>
		</ul>
	</div>
	<div id="main">
	{% block content %}Default main content{% endblock %}
	</div>
</body>
<html>