draft/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
	url(r'^getathletes', views.league_get_available, name='league_get_available'),
	url(r'^getplayers', views.league_get_players, name='league_get_players'),
]

rowing/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^runleague/', include('runleague.urls', namespace="runleague")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^postman/', include('postman.urls', namespace="postman", app_name="postman")),
    url(r'^draft/', include('draft.urls', namespace="draft")),
	]

runleague/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^about', views.AboutView.as_view(), name='about'),
	url(r'^maketeam/success', views.TeamSuccessView.as_view(), name='make_team_success'),
	url(r'^newleague/success', views.LeagueSuccessView.as_view(), name='make_league_success'),
    url(r'^team/(?P<team_id>[0-9]+)/$', views.team_detail, name='team_detail'),
    url(r'^team', views.my_team_detail, name='my_team_detail'),
    url(r'^(?P<page_id>[0-9]+)/$', views.team_page, name='team_page'),
	url(r'^editteam/add/(?P<athlete_id>[0-9]+)/$', views.athlete_add, name='athlete_add'),
	url(r'^editteam/remove/(?P<athlete_id>[0-9]+)/$', views.athlete_remove, name='athlete_remove'),
	url(r'^editname', views.team_edit_name, name='team_edit_name'),
	url(r'^addathlete', views.team_add_athlete, name='team_add_athlete'),
	url(r'^removeathlete', views.team_remove_athlete, name='team_remove_athlete'),
	url(r'^get_athletes(.)*', views.team_get_athletes, name='team_athlete_get'),
	url(r'^tradeathlete', views.team_trade_athlete, name='team_trade_athlete'),
    url(r'^signin', views.sign_in, name='sign_in'),
    url(r'^signout', views.sign_out, name='sign_out'),
	url(r'^athlete/(?P<athlete_id>[0-9]+)/$', views.athlete_detail, name='athlete_detail'),
	url(r'^signup', views.sign_up, name='sign_up'),
	url(r'^league/(?P<league_id>[0-9]+)/$', views.league_detail, name='league_detail'),
	url(r'^league', views.my_league_detail, name='my_league_detail'),
	url(r'^editleague', views.league_edit, name='league_edit'),
	url(r'^kickuser/(?P<user_id>[0-9]+)/$', views.league_kick_user, name='league_kick_user'),
	url(r'^maketeam', views.make_team, name='make_team'),
	url(r'^newleague', views.new_league, name='new_league'),
    ]

draft/models.py
from django.db import models
from runleague import *

runleague/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *
from collections import OrderedDict

class LoginForm(forms.Form):
	username = forms.CharField(max_length=100)
	password = forms.CharField(max_length=100, widget=forms.PasswordInput)

class SignupForm(UserCreationForm):
	email = forms.EmailField(label="Email address", required=True, help_text="Required.")
	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")
		
	def save(self, commit=True):
		user = super(SignupForm, self).save(commit=False)
		user.email = self.cleaned_data["email"]
		if commit:
			user.save()
		return user

class ChooseLeagueForm(forms.Form):
	teamname = forms.CharField(label="Team name", max_length=100)
	def __init__(self, *args, **kwargs):
		super(ChooseLeagueForm, self).__init__(*args, **kwargs)
		openpks = [l.pk for l in League.objects.open_leagues()]
		self.fields = OrderedDict([('league',forms.ModelChoiceField(queryset=League.objects.filter(pk__in=openpks))),('teamname',self.fields['teamname'])])
		
class LeagueForm(forms.ModelForm):
	class Meta:
		model = League
		fields = ['name', 'size']

class TradePlayerForm(forms.Form):
	def __init__(self, user, *args, **kwargs):
		self.user = user
		super(TradePlayerForm, self).__init__(*args, **kwargs)
		self.fields['teams'] = forms.ChoiceField(label="Trade with", widget=forms.Select(attrs={'onchange':'get_athletes();'}), choices=[(-1,"Choose Team")]+[(u.team_set.first().id, u.team_set.first().name) for u in user.members.first().members.all() if u != self.user])
		self.fields['yourathletes'] = forms.MultipleChoiceField(label="Trade", choices=[(a,a) for a in user.team_set.first().athletes.all()])
		self.fields['theirathletes'] = forms.MultipleChoiceField(label="For", choices=[(a,a) for a in Athlete.objects.all()])

class EditNameForm(forms.Form):
	name = forms.CharField(label = "New name", max_length=100)

draft/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.serializers import serialize
import simplejson

def main(request):
    return render(request, 'draft/main.html', {})

def league_get_available(request):
	league = request.user.members.first()
	return HttpResponse(serialize('json', league.available_athletes()))

def league_get_players(request):
	league = request.user.members.first()
	return HttpResponse(serialize('json', league.schedule.get_players()))

runleague/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import user_passes_test
import collections, simplejson

# Create your views here.
from .models import *
from .forms import *

def has_team(user):
	if hasattr(user, 'team_set'):
		return len(user.team_set.all()) > 0
	return False

def owns_league(user):
	if hasattr(user, 'owner'):
		return len(user.owner.all()) > 0
	return False

class IndexView(generic.TemplateView):
	template_name = 'runleague/about.html'

class AboutView(generic.TemplateView):
	template_name = 'runleague/about.html'
	
class TeamSuccessView(generic.TemplateView):
	template_name = 'runleague/make_team_success.html'
		
class LeagueSuccessView(generic.TemplateView):
	template_name = 'runleague/make_league_success.html'
	
def team_detail(request, team_id):
	team = Team.objects.get(pk=team_id)
	referer = u'/' + u'/'.join(request.META.get('HTTP_REFERER').split('/')[3:])
	context = {'team':team, 'referer':referer}
	return render(request, 'runleague/team_detail.html', context)

def my_team_detail(request):
	if request.user.is_authenticated():
		team = request.user.team_set.first()
	else:
		team = None
	referer = u'/' + u'/'.join(request.META.get('HTTP_REFERER').split('/')[3:])
	context = {'team':team, 'referer':referer}
	return render(request, 'runleague/team_detail.html', context)

def team_page(request, page_id):
	team_list = Team.objects.all()[50*int(page_id)-50:50*int(page_id)]
	next_page = int(page_id) + 1
	last_page = int(page_id) - 1
	max_page = 1 + len(Team.objects.all()) / 50
	page = {'next':next_page, 'last':last_page, 'max':max_page, 'id':page_id}
	context = {'team_list':team_list, 'page':page}
	return render(request, 'runleague/team_page.html', context)

@user_passes_test(has_team, login_url='/runleague/signin', redirect_field_name=None)
def team_add_athlete(request):
	team = request.user.team_set.first()
	schools = Athlete.objects.order_by().values('school').distinct()
	not_added = {}
	for school in schools:
		temp = Athlete.objects.filter(school=school['school'])
		not_added[school['school']] = []
		for athlete in temp:
			if not (athlete in team.league.taken_athletes()):
				not_added[school['school']].append(athlete)
	not_added = collections.OrderedDict(sorted(not_added.items()))
	
	context = {'team':team, 'not_added':not_added}
	return render(request, 'runleague/team_add_athlete.html', context)

@user_passes_test(has_team, login_url='/runleague/signin', redirect_field_name=None)
def team_remove_athlete(request):
	team = request.user.team_set.first()
	schools = Athlete.objects.order_by().values('school').distinct()
	not_added = {}
	for school in schools:
		temp = Athlete.objects.filter(school=school['school'])
		not_added[school['school']] = []
		for athlete in temp:
			if not (athlete in team.league.taken_athletes()):
				not_added[school['school']].append(athlete)
	not_added = collections.OrderedDict(sorted(not_added.items()))
	
	context = {'team':team, 'not_added':not_added}
	return render(request, 'runleague/team_remove_athlete.html', context)

@user_passes_test(has_team, login_url='/runleague/signin', redirect_field_name=None)
def team_trade_athlete(request):
	if request.method == "GET":
		form = TradePlayerForm(request.user) 
	elif request.method == "POST":
		form = TradePlayerForm(request.user, request.POST)
		return render(request, 'runleague/team_trade_sent.html', {})
	return render(request, 'runleague/team_trade_athlete.html', {'form':form})

def team_get_athletes(request, teamid):
	if request.GET.get('teamid'):
		teamid = request.GET.get('teamid')
		athletes = [unicode(a) for a in Team.objects.get(pk=teamid).athletes.all()]
	else:
		athletes = None
	
	if not athletes:
		athletes = ["No athletes"]

	return HttpResponse(simplejson.dumps(athletes))
	
@user_passes_test(has_team, login_url='/runleague/signin', redirect_field_name=None)
def team_edit_name(request):
	if request.method == "GET":
		form = EditNameForm()
	elif request.method == "POST":
		form = EditNameForm(request.POST)
		if form.is_valid():
			t = request.user.team_set.first()
			t.name = form.cleaned_data['name']
			t.save()
			return redirect('/runleague/team')
	return render(request, 'runleague/team_edit_name.html', {'form':form, 'team':request.user.team_set.first()})
	
@user_passes_test(has_team, login_url='/runleague/signin', redirect_field_name=None)
def athlete_add(request, athlete_id):
	team = request.user.team_set.first()
	athlete = Athlete.objects.get(pk=athlete_id)
	if not (athlete in team.league.taken_athletes()):
		team.athletes.add(athlete)
	not_added = {}
	schools = Athlete.objects.order_by().values('school').distinct()
	for school in schools:
		temp = Athlete.objects.filter(school=school['school'])
		not_added[school['school']] = []
		for athlete in temp:
			if not (athlete in team.league.taken_athletes()):
				not_added[school['school']].append(athlete)
	not_added = collections.OrderedDict(sorted(not_added.items()))
	
	context = {'team':team, 'not_added':not_added}
	return render(request, 'runleague/team_detail.html', context)

@user_passes_test(has_team, login_url='/runleague/signin', redirect_field_name=None)
def athlete_remove(request, athlete_id):
	team = request.user.team_set.first()
	athlete = Athlete.objects.get(pk=athlete_id)
	if athlete in team.athletes.all():
		team.athletes.remove(athlete)
	not_added = team.league.available_athletes()
	context = {'team':team, 'not_added':not_added}
	return render(request, 'runleague/team_detail.html', context)

def athlete_detail(request, athlete_id):
	rower = get_object_or_404(Athlete, pk=athlete_id)
	referer = u'/' + u'/'.join(request.META.get('HTTP_REFERER').split('/')[3:])
	context = {'rower':rower, 'referer':referer}
	return render(request, 'runleague/athlete_detail.html', context)

def athlete_page(request, page_id):
	rower_list = Athlete.objects.all()[50*int(page_id)-50:50*int(page_id)]
	next_page = int(page_id) + 1
	last_page = int(page_id) - 1
	max_page = 1 + len(Athlete.objects.all()) / 50
	page = {'next':next_page, 'last':last_page, 'max':max_page, 'id':page_id}
	context = {'rower_list':rower_list, 'page':page}
	return render(request, 'runleague/athlete_page.html', context)

def sign_in(request):
	if request.method == 'GET':
		form = LoginForm()
		message = ''
	elif request.method == 'POST':
		message = 'Invalid credentials'
		form = LoginForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				if user.is_active:
					login(request, user)
					message = 'Login successful'
	return render(request, 'runleague/signin.html', {'form':form, 'message':message})
	
def sign_out(request):
	logout(request)
	return render(request, 'runleague/signout.html',{})
	
def sign_up(request):
	if request.method == 'GET':
		form = SignupForm()
	elif request.method == 'POST':
		form = SignupForm(request.POST)
		if form.is_valid():
			user = form.save()
			return render(request, 'runleague/signin.html', {'form':LoginForm(),'message':str(user)+" successfully created"})
	return render(request, 'runleague/signup.html', {'form':form})

def league_detail(request, league_id):
	league = League.objects.get(pk=league_id)
	referer = u'/' + u'/'.join(request.META.get('HTTP_REFERER').split('/')[3:])
	context = {'league':league, 'referer':referer}
	return render(request, 'runleague/league_detail.html', context)

def my_league_detail(request):
	if hasattr(request.user, 'members'):
		league = request.user.members.first()
	else:
		league = None
	referer = u'/' + u'/'.join(request.META.get('HTTP_REFERER').split('/')[3:])
	context = {'league':league, 'referer':referer}
	return render(request, 'runleague/league_detail.html', context)

@user_passes_test(owns_league, login_url='/runleague/league_detail', redirect_field_name=None)
def league_edit(request):
	league = request.user.owner.first()
	referer = u'/' + u'/'.join(request.META.get('HTTP_REFERER').split('/')[3:])
	return render(request, 'runleague/league_edit.html', {'league':league, 'referer':referer})

@user_passes_test(has_team, login_url='/runleague/league_detail', redirect_field_name=None)
def league_kick_user(request, user_id):
	u = User.objects.get(pk=user_id)
	l = request.user.members.first()

	if u.id != request.user.id and l.owner != request.user.id:
		return redirect("/runleague/league")
	
	if len(l.members.all()) <= 1:
		l.delete()
	elif l.owner == u:
		l.members.remove(u)
		l.owner = l.members.first()
		l.save()
	else:
		l.members.remove(u)
		l.save()

	if u.team_set.first():
		u.team_set.first().delete()
	return render(request, 'runleague/user_kicked.html', {'user':u, 'league':l})

def make_team(request):
	if request.method == 'GET':
		form = ChooseLeagueForm()
	elif request.method == 'POST':
		form = ChooseLeagueForm(request.POST)
		if form.is_valid():
			l = form.cleaned_data.get('league')
			teamname = form.cleaned_data.get('teamname')
			request.user.team_set.add(Team(user = request.user, name=teamname, league=l))
			request.user.members.add(l)
			return render(request, 'runleague/make_team_success.html', {})
	return render(request, 'runleague/make_team.html', {'form':form})

def new_league(request):
	if request.method == 'GET':
		form = LeagueForm()
	elif request.method == 'POST':
		form = LeagueForm(request.POST)
		if form.is_valid():
			l = form.save(commit=False)
			l.owner = request.user
			l.save()
			Schedule(league=l, turn=0).save()
			request.user.members.add(l)
			request.user.team_set.add(Team(user = request.user, name="Team " + str(request.user.username), league=l))
			context = {}
			return render(request, 'runleague/make_league_success.html', context)

runleague/templates/runleague/about.html
{% extends 'runleague/base.html' %}

{% block title %}About{% endblock %}

{% block content %}

<p>Welcome to fantasy rowing!</p>

{% endblock %}

runleague/templates/runleague/league_detail.html
{% extends 'runleague/base.html' %}

{% block title %}League{% endblock %}

{% block content %}

{% if user.members.first %}

<h3>{{ league.name }}</h3>
{% if user.owner.first == league %}
<a href="{% url 'runleague:league_edit' %}">Edit league..</a>
{% endif %}
<h4>Teams</h4>
<table border='0'>
<tr><th>#</th><th>Team</th><th>User</th></tr>
{% for u in league.members.all %}
	<tr>
	<td>{{forloop.counter0|add:"1"}}</td>
	<td>{{u.team_set.first.name}}</td>
	<td>{{u}}</td>
	</tr>
{% endfor %}
</table>

</br>
<a onclick="return confirm('Are you sure you want to leave your league?');" href="{% url 'runleague:league_kick_user' user.id %}">Leave league</a>
</br>

<a href="{{referer}}">Back</a>

{% else %}

<p>You are not in a league right now.</p>
<a href="{% url 'runleague:make_team' %}">Join a league</a>

{% endif %}

{% endblock %}

runleague/templates/runleague/league_edit.html
{% extends 'runleague/base.html' %}

{% block title %}League{% endblock %}

{% block content %}

{% if user.owner.first %}

<h3>{{ league.name }}</h3>

<h4>Teams</h4>
<table border='0'>
<tr><th>#</th><th>Team</th><th>User</th><th></th></tr>
{% for u in league.members.all %}
	{% if u != user %}
	<tr>
	<td>{{forloop.counter0|add:"1"}}</td>
	<td>{{u.team_set.first.name}}</td>
	<td>{{u}}</td>
	<td><a href="{% url 'runleague:league_kick_user' u.id %}">Kick</a>
	</tr>
	{% endif %}
{% endfor %}
</table>

<a href="{{referer}}">Back</a>

{% else %}

<p>You are not in a league right now.</p>
<a href="{% url 'runleague:make_team' %}">Join a league</a>

{% endif %}

{% endblock %}

runleague/templates/runleague/make_league_success.html
{% extends 'runleague/base.html' %}

{% block content %}

<p>League successfully created!</p>
<a href="{% url 'runleague:my_league_detail' %}">Go to your League.</a>

{% endblock %}

runleague/templates/runleague/newleague.html
{% extends 'runleague/base.html' %}

{% block title %}Create League{% endblock %}

{% block content %}

{% if user.is_authenticated %}
	{% if user.members.first %}
	<p>You are already in the {{user.league}} league.</p>
	{% else%}
	<h3>New League</h3>
	<form action='newleague' method='post'>
		{% csrf_token %}
		{{form.as_p}}
		<input type='submit' value='Submit'>
		{% csrf_token %}
	</form>
	{% endif %}
{% else %}
<p>You are not signed in. To make a league please <a href="{% url 'runleague:sign_in' %}">sign in.</a></p>
{% endif %}

{% endblock %}

runleague/templates/runleague/team_add_athlete.html
{% extends 'runleague/base.html' %}

{% block title %}Team{% endblock %}

{% block content %}

<h2>{{ team.name }}</h2>

<h3>Add</h3>
{% for school, athletes in not_added.iteritems %}
<h4>{{school}}</h4>
<ul>
	{% for athlete in athletes %}
		<li>
		<a href="{% url 'runleague:athlete_detail' athlete.id %}">{{athlete}}</a>
		<form action="{% url 'runleague:athlete_add' athlete.id %}" method="POST">
		<input type='submit' value='Add'>
		{% csrf_token %}
		</form>
		</li>
	{% endfor %}
</ul>
{% endfor %}

<a href="{% url 'runleague:my_team_detail'%}">Back</a>

{% endblock %}

runleague/templates/runleague/team_add_player.html
{% extends 'runleague/base.html' %}

{% block title %}Team{% endblock %}

{% block main_block %}

<h2>{{ team.name }}</h2>

<h3>Add</h3>
{% for school, athletes in not_added.iteritems %}
<h4>{{school}}</h4>
<ul>
	{% for athlete in athletes %}
		<li>
		<a href="{% url 'runleague:athlete_detail' athlete.id %}">{{athlete}}</a>
		<form action="{% url 'runleague:athlete_add' athlete.id %}" method="POST">
		<input type='submit' value='Add'>
		{% csrf_token %}
		</form>
		</li>
	{% endfor %}
</ul>
{% endfor %}

<a href="{% url 'runleague:team_edit'%}">Back</a>

{% endblock %}

runleague/templates/runleague/team_detail.html
{% extends 'runleague/base.html' %}

{% block title %}Team{% endblock %}

{% block content %}

{% if user.team_set.first %}

<h3>{{ team.name }}</h3>

<a href="{% url 'runleague:team_edit_name' %}">Edit name</a></br>

<h4>Athletes</h4>
<table border='0'>
<tr><th>#</th><th>School</th><th>Athlete</th><th>Height</th><th>Weight</th><th>Hometown</th><th>High School</th></tr>
{% for athlete in team.athletes.all %}
	<tr>
	<td>{{forloop.counter0|add:"1"}}</td>
	<td>{{athlete.school}}</td>
	<td><a href="{% url 'runleague:athlete_detail' athlete.id %}">{{athlete}}</a></td>
	<td>{{athlete.height}}</td>
	<td>{{athlete.weight}}</td>
	<td>{{athlete.hometown}}</td>
	<td>{{athlete.high_school}}</td>
	</tr>
{% endfor %}
</table>
{% if user.is_authenticated and user.team_set.first == team %}
</br>
<a href="{% url 'runleague:team_add_athlete' %}">Add Players</a></br>
<a href="{% url 'runleague:team_remove_athlete' %}">Remove Players</a></br>
<a href="{% url 'runleague:team_trade_athlete' %}">Trade Players</a></br>
</br>
{% endif %}
<a href="{{referer}}">Back</a>

{% else %}

<p>You do not have a team right now.</p>
<a href="{% url 'runleague:make_team' %}">Join a league</a>

{% endif %}

{% endblock %}

runleague/templates/runleague/team_page.html
{% extends 'runleague/base.html' %}

{% block title %}Team{% endblock %}

{% block content %}

{% if team_list %}
<ul>
	{% for team in team_list %}
	<li><a href="{% url 'runleague:team_detail' team.id %}">{{team.name}}</a></li>
	{% endfor %}
</ul>

<p style="font-size:20;">
{% if page.last > 0%}
<a href="{% url 'runleague:team_page' 1%}">1</a>
...
<a href="{% url 'runleague:team_page' page.last %}"><</a>
{% endif %}
{% if page.next <= page.max %}
<a href="{% url 'runleague:team_page' page.next %}">></a>
...
<a href="{% url 'runleague:team_page' page.max%}">{{page.max}}</a>
{% endif %}
</p>

{% else %}
<p>No teams are available.</p>
{% endif %}

{% endblock %}

runleague/templates/runleague/team_remove_athlete.html
{% extends 'runleague/base.html' %}

{% block title %}Team{% endblock %}

{% block content %}

<h2>{{ team.name }}</h2>

<h3>Remove</h3>
<ul>
{% for athlete in team.athletes.all %}
	<li>
	<a href="{% url 'runleague:athlete_detail' athlete.id %}">{{athlete}}</a>
	<form action="{% url 'runleague:athlete_remove' athlete.id %}" method="POST">
	<input type='submit' value='Remove'>
	{% csrf_token %}
	</form>
	</li>
{% endfor %}
</ul>

<a href="{% url 'runleague:my_team_detail' %}">Back</a>

{% endblock %}

runleague/templates/runleague/team_remove_player.html
{% extends 'runleague/base.html' %}

{% block title %}Team{% endblock %}

{% block main_block %}

<h2>{{ team.name }}</h2>

<h3>Remove</h3>
<ul>
{% for athlete in team.athletes.all %}
	<li>
	<a href="{% url 'runleague:athlete_detail' athlete.id %}">{{athlete}}</a>
	<form action="{% url 'runleague:athlete_remove' athlete.id %}" method="POST">
	<input type='submit' value='Remove'>
	{% csrf_token %}
	</form>
	</li>
{% endfor %}
</ul>

<a href="{% url 'runleague:team_edit' %}">Back</a>

{% endblock %}

runleague/templates/runleague/team_trade_athlete.html
{% extends 'runleague/base.html' %}

{% block title %}Trade{% endblock %}

{% block extrahead %}
{% load staticfiles %}
<script type="text/javascript" src="{% static 'jquery-1.11.13.js' %}"></script>
<script type="text/javascript">
function get_athletes(){
	var xhttp;
	if(window.XMLHttpRequest){
		xhttp = new XMLHttpRequest();
	} else {
		xhttp = new ActiveXObject("Microsoft.XMLHTTP");
	}

	var teamid = document.getElementById("id_teams").value;
	var url = "/runleague/get_athletes?teamid=" + escape(teamid);
	xhttp.open("GET", url, true);
	xhttp.onreadystatechange = function() {
		if(xhttp.readyState == 4 && xhttp.status == 200) {
			var athletes = JSON.parse(xhttp.responseText);
			select = $('select[id=id_theirathletes]');
			select.find('option').remove();
			for (var a in athletes) {
				select.append($('<option value="'+athletes[a]+'">'+athletes[a]+'</option>'));
			}
		}
	};
	xhttp.send();
}
</script>
{% endblock %}

{% block content %}

<h2>{{ team.name }}</h2>

<h3>Trade</h3>

<form action="{% url 'runleague:team_trade_athlete' %}" method="POST">
	{{form.as_p}}
	<input type='submit' value='Trade'>
	{% csrf_token %}
</form>
<a href="{% url 'runleague:my_team_detail' %}">Back</a>

{% endblock %}

runleague/templates/runleague/team_trade_player.html
{% extends 'runleague/base.html' %}

{% block title %}Team{% endblock %}

{% block main_block %}

<h2>{{ team.name }}</h2>

<h3>Trade</h3>
<form

<a href="{% url 'runleague:team_edit' %}">Back</a>

{% endblock %}

runleague/templates/runleague/team_trade_sent.html
{% extends 'runleague/base.html' %}

{% block title %}Trade{% endblock %}

{% block content %}

Trade request sent

{% endblock %}